version: "3"
services:
  webserver:
    container_name: webserver
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - leke-net
    volumes:
      - ./backmeup:/var/www/vhosts/backmeup
      - ./backmeup-be:/var/www/vhosts/backmeup-be
    depends_on:
      - notify
      - backmeup
      - backmeup-api
  notify:
    container_name: notify
    build:
      context: ./notify
      dockerfile: Dockerfile.dev
    networks:
      - leke-net
    volumes:
      - ./notify:/usr/src/app
      - /usr/src/app/node_modules
  backmeup:
    container_name: backmeup
    build:
      context: ./backmeup-fe
      dockerfile: Dockerfile.dev
    networks:
      - leke-net
    volumes:
      - ./backmeup-fe:/app
      - /app/node_modules
  backmeup-api:
    container_name: backmeup-api
    build:
      context: ./backmeup-be
      dockerfile: Dockerfile.dev
    networks:
      - leke-net
    volumes:
      - ./backmeup-be:/usr/src/app
networks:
  leke-net:
    driver: bridge
