version: "3"
services:
  webserver:
    container_name: webserver
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - leke-net
    volumes:
      - ./backmeup-be:/var/www/vhosts/backmeup-be
      - ./certbot:/var/www/certbot
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    depends_on:
      - backmeup
      - backmeup-api
  backmeup:
    container_name: backmeup
    build:
      context: ./backmeup-fe
      dockerfile: Dockerfile
    networks:
      - leke-net
    volumes:
      - ./backmeup-fe:/app
      - /app/node_modules
  backmeup-api:
    container_name: backmeup-api
    build:
      context: ./backmeup-be
      dockerfile: Dockerfile
    networks:
      - leke-net
    volumes:
      - ./backmeup-be:/usr/src/app
      - /usr/src/app/node_modules
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot:/var/www/certbot
  #     - ./certbot-etc:/etc/letsencrypt
  #     - ./certbot-var:/var/lib/letsencrypt
  #   depends_on:
  #     - webserver
  #   networks:
  #     - leke-net
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email olamileke.dev@gmail.com --agree-tos --no-eff-email --force-renewal -d backmeup.olamileke.me
networks:
  leke-net:
    driver: bridge
