version: "3"
services:
  webserver:
    container_name: webserver
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - leke-net
    volumes:
      - ./certbot/root:/var/www/certbot
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./certbot/dhparam:/etc/ssl/certs
    depends_on:
      - notify
      - noir
      - crest
      - cyclone
  notify:
    container_name: notify
    image: olamileke/notify
    networks:
      - leke-net
    volumes:
      - ./env/notify.env:/usr/src/app/.env
  noir:
    container_name: noir
    image: olamileke/bayitt-noir
    networks:
      - leke-net
    volumes:
      - ./env/noir.env:/usr/src/app/.env
    env_file:
      - ./env/noir.env
  crest:
    container_name: crest
    image: olamileke/bayitt-crest
    networks:
      - leke-net
    volumes:
      - ./env/crest.env:/usr/src/app/.env
  pluto:
    container_name: pluto
    image: olamileke/bayitt-pluto
    networks:
      - leke-net
    env_file:
      - ./env/pluto.env
  cyclone:
    container_name: cyclone
    image: olamileke/cyclone
    networks:
      - leke-net
    volumes:
      - ./env/cyclone.env:/app/.env
  # certbot:
  #   image: certbot/dns-digitalocean
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/root:/var/www/certbot
  #     - ./certbot/etc:/etc/letsencrypt
  #     - ./certbot/var:/var/lib/letsencrypt
  #     - ./certbot/credentials:/credentials
  #   depends_on:
  #     - webserver
  #   networks:
  #     - leke-net
  #   command: certonly --dns-digitalocean --dns-digitalocean-credentials /credentials/credentials.ini -d olamileke.dev -d *.olamileke.dev
networks:
  leke-net:
    driver: bridge
